#
# R77Driver Makefile
#
# This makefile supports both WDK build environment and standalone builds.
#

#
# Standard WDK makefile inclusion
# Use this with the WDK build environment (build -cZg)
#
!INCLUDE $(NTMAKEENV)\makefile.def
